#!/usr/bin/env bash
#
# migrate-to-coga.sh — migrate an existing Relay-installed repo to Coga.
#
# Run this from the ROOT of a host repo that still uses the old `relay` layout
# (a `relay-os/` workspace and/or a `relay.toml`). It performs the on-disk half
# of the relay->coga rename for that repo:
#
#   relay-os/               -> coga/                (workspace dir)
#   relay.toml              -> coga.toml            (shared config)
#   relay.local.toml        -> coga.local.toml      (machine-local config)
#   coga/contexts/relay/    -> coga/contexts/coga/  (local context overrides)
#   coga/skills/relay/      -> coga/skills/coga/     (local skill overrides)
#   <!-- relay:blackboard --> -> <!-- coga:blackboard -->   (ticket fence)
#   contexts/skills refs `relay/<ns>` -> `coga/<ns>` (frontmatter only)
#   RELAY_REPO_URL          -> COGA_REPO_URL        (config / .gitignore)
#
# It deliberately does NOT rewrite prose, historical PR URLs, or source-path
# references in task bodies — only the structural bits Coga parses. The frontmatter
# ref sweep is scoped to the YAML region between the first two `---` lines, so a
# `relay/...` URL or path elsewhere in a ticket is left alone.
#
# After it runs, reinstall the CLI and refresh the vendored copy:
#   pip install -e .   (or pipx install --force .)   then   coga init --update
#
# Idempotent: re-running on an already-migrated repo (coga/ present, no relay-os/)
# is a no-op. Use --dry-run to preview, --force to proceed on a dirty tree.

set -euo pipefail

DRY_RUN=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --force)   FORCE=1 ;;
    -h|--help)
      sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "unknown arg: $arg (try --dry-run, --force, --help)" >&2; exit 2 ;;
  esac
done

say()  { printf '%s\n' "$*"; }
step() { printf '  • %s\n' "$*"; }

# run CMD... — execute, or just print under --dry-run.
run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '    [dry-run] '; printf '%q ' "$@"; printf '\n'
  else
    "$@"
  fi
}

# --- preconditions ------------------------------------------------------------

if [ ! -d .git ] && ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "error: run this from the root of a git repo." >&2
  exit 1
fi

if [ ! -d relay-os ] && [ ! -f relay.toml ]; then
  if [ -d coga ] || [ -f coga.toml ]; then
    say "Already on Coga (no relay-os/ or relay.toml found). Nothing to do."
    exit 0
  fi
  echo "error: no relay-os/ or relay.toml here — is this a Relay host repo root?" >&2
  exit 1
fi

if [ "$FORCE" -eq 0 ] && [ "$DRY_RUN" -eq 0 ] && [ -n "$(git status --porcelain)" ]; then
  echo "error: working tree is dirty. Commit/stash first, or pass --force." >&2
  exit 1
fi

IS_GIT_MV=1  # prefer `git mv` so history follows; fall back to plain mv.
gmv() {  # gmv SRC DST
  if [ "$IS_GIT_MV" -eq 1 ] && git ls-files --error-unmatch "$1" >/dev/null 2>&1; then
    run git mv "$1" "$2"
  else
    run mv "$1" "$2"
  fi
}

say "Migrating this repo: relay -> coga$([ "$DRY_RUN" -eq 1 ] && echo '  (dry-run)')"

# --- 1. workspace + config dir/file renames -----------------------------------

if [ -d relay-os ]; then
  step "relay-os/ -> coga/"
  # Plain mv moves tracked + gitignored (.relay/, .agent-skills/) content together;
  # `git add -A` afterward records the tracked renames.
  run mv relay-os coga
fi
[ -f relay.toml ]       && { step "relay.toml -> coga.toml";             run mv relay.toml coga.toml; }
[ -f relay.local.toml ] && { step "relay.local.toml -> coga.local.toml"; run mv relay.local.toml coga.local.toml; }

# --- 2. inner namespace overrides (coga/contexts/relay, coga/skills/relay) -----

for ns in contexts skills; do
  if [ -d "coga/$ns/relay" ]; then
    if [ -e "coga/$ns/coga" ]; then
      echo "    warning: coga/$ns/coga already exists — leaving coga/$ns/relay in place (resolve by hand)." >&2
    else
      step "coga/$ns/relay/ -> coga/$ns/coga/"
      gmv "coga/$ns/relay" "coga/$ns/coga"
    fi
  fi
done

# --- 3. drop regenerated vendored dirs (rebuilt by `coga init --update`) -------

for d in coga/.relay coga/.agent-skills; do
  [ -e "$d" ] && { step "remove $d (regenerated by coga init --update)"; run rm -rf "$d"; }
done

# --- 4. content edits: blackboard fence + frontmatter refs --------------------

# Fence: unambiguous string, safe to replace anywhere in a ticket body.
# Frontmatter refs: rewrite `relay/<ns>` -> `coga/<ns>` ONLY inside the YAML
# region (between the first two `---` lines), where a `relay/...` token is always
# a context/skill ref — never a URL or source path.
edit_markdown() {
  local root="$1"
  [ -d "$root" ] || return 0
  find "$root" -type f -name '*.md' -print0 | while IFS= read -r -d '' f; do
    if [ "$DRY_RUN" -eq 1 ]; then
      if grep -qE '<!-- relay:blackboard -->|^[[:space:]]*-?[[:space:]]*[a-z]*:?[[:space:]]*relay/' "$f"; then
        printf '    [dry-run] edit %s\n' "$f"
      fi
      continue
    fi
    perl -0777 -pi -e '
      # split off the YAML frontmatter region (first --- ... \n---\n)
      if (s/\A(---\n.*?\n---\n)//s) {
        my $fm = $1;
        $fm =~ s{(^|[\s\[,>])relay/}{$1coga/}g;   # refs only appear in frontmatter
        $_ = $fm . $_;
      }
      s/<!-- relay:blackboard -->/<!-- coga:blackboard -->/g;   # body fence
    ' "$f"
  done
}
step "rewrite blackboard fence + frontmatter relay/<ns> refs under coga/"
edit_markdown coga

# --- 5. config / gitignore token renames --------------------------------------

for f in coga.toml coga.local.toml .gitignore; do
  [ -f "$f" ] || continue
  if grep -qE 'RELAY_REPO_URL|relay\.local\.toml|relay-os' "$f"; then
    step "rename relay tokens in $f"
    if [ "$DRY_RUN" -eq 0 ]; then
      perl -pi -e '
        s/\bRELAY_REPO_URL\b/COGA_REPO_URL/g;
        s/\brelay\.local\.toml\b/coga.local.toml/g;
        s{\brelay-os\b}{coga}g;
      ' "$f"
    fi
  fi
done

# --- 6. stage + next steps ----------------------------------------------------

if [ "$DRY_RUN" -eq 0 ]; then
  run git add -A
fi

say ""
say "Done. Next steps (manual — they touch your environment):"
say "  1. Reinstall the CLI:   pip install -e .   (or  pipx install --force .)"
say "  2. Refresh vendored CLI + batteries:   coga init --update"
say "  3. Sanity check:        coga validate  &&  coga status"
say "  4. Review the staged diff, then commit."
if [ "$DRY_RUN" -eq 1 ]; then
  say ""
  say "(dry-run: nothing was changed.)"
fi

exit 0
